title: Ziqing Ma
url: "https://mazinggg.github.io"
baseurl: "/maziqing/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Resume"
   link: "ZiqingMa.pdf"
 - name: "Contact"
   link: "contact"
