title: Ziqing Ma
url: "https://mazinggg.github.io"
baseurl: "/maziqing/"

tracking_id: #

footer: yes
footer_url: "https://mazinggg.github.io/maziqing/contact"
footer_text: "Page designed by Ziqing Ma"

sass:
    style: normal
    sass_dir: _sass

nav:
 - name: "Home"
   link: "index"
 - name: "Curriculum Vitae"
   link: "ZiqingMa.pdf"
 - name: "Contact me"
   link: "contact"
